### ISSUE TITLE
Crash when using survive 3.20, unionlib 3.30 on the server.

### ISSUE THREAD

**Issue by WhyAreAllTheseTaken** [Stereowalker/Survive#107]
When using the mod on a server, union lib causes a crash by accessing client-side code on the server.

The issue occurs at com.stereowalker.unionlib.UnionLib.<init>(UnionLib.java:79). The class net.minecraft.client.gui.screen.Screen is still loaded on the client side.

Crash Details:

`07.04 15:57:53 [Server] INFO ---- Minecraft Crash Report ----
07.04 15:57:53 [Server] INFO // Ooh. Shiny.
07.04 15:57:53 [Server] INFO Time: 4/7/21 3:57 PM
07.04 15:57:53 [Server] INFO Description: Mod loading error has occurred
07.04 15:57:53 [Server] INFO java.lang.Exception: Mod Loading has failed
07.04 15:57:53 [Server] INFO at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
07.04 15:57:53 [Server] INFO at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
07.04 15:57:53 [Server] INFO at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
07.04 15:57:53 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[custom.jar:36.1] {}
07.04 15:57:53 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
07.04 15:57:53 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
07.04 15:57:53 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
07.04 15:57:53 [Server] INFO at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
07.04 15:57:53 [Server] INFO at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
07.04 15:57:53 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [custom.jar:?] {}
07.04 15:57:53 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [custom.jar:?] {}
07.04 15:57:53 [Server] INFO at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [custom.jar:?] {}
07.04 15:57:53 [Server] INFO A detailed walkthrough of the error, its code path and all known details is as follows:
07.04 15:57:53 [Server] INFO ---------------------------------------------------------------------------------------
07.04 15:57:53 [Server] INFO -- Head --
07.04 15:57:53 [Server] INFO Thread: main
07.04 15:57:53 [Server] INFO Stacktrace:
07.04 15:57:53 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[custom.jar:36.1] {}
07.04 15:57:53 [Server] INFO -- MOD unionlib --
07.04 15:57:53 [Server] INFO Details:
07.04 15:57:53 [Server] INFO Mod File: UnionLib-1.16.5-3.3.0.jar
07.04 15:57:53 [Server] INFO Failure message: UnionLib (unionlib) has failed to load correctly
07.04 15:57:53 [Server] INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
07.04 15:57:53 [Server] INFO Mod Version: 3.3.0
07.04 15:57:53 [Server] INFO Mod Issue URL: https://github.com/Stereowalker/C.O.M.B.A.T./issues
07.04 15:57:53 [Server] INFO Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
07.04 15:57:53 [Server] INFO Stacktrace:
07.04 15:57:53 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[custom.jar:36.1] {}
07.04 15:57:53 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
07.04 15:57:53 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
07.04 15:57:53 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
07.04 15:57:53 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
07.04 15:57:53 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
07.04 15:57:53 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at com.stereowalker.unionlib.UnionLib.<init>(UnionLib.java:79) ~[unionlib:3.3.0] {re:classloading}
07.04 15:57:53 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
07.04 15:57:53 [Server] INFO at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
07.04 15:57:53 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_211] {}
07.04 15:57:53 [Server] INFO -- System Details --
07.04 15:57:53 [Server] INFO Details:
07.04 15:57:53 [Server] INFO Minecraft Version: 1.16.5
07.04 15:57:53 [Server] INFO Minecraft Version ID: 1.16.5
07.04 15:57:53 [Server] INFO Operating System: Linux (amd64) version 4.19-ovh-xxxx-std-ipv6-64
07.04 15:57:53 [Server] INFO Java Version: 1.8.0_211, Oracle Corporation
07.04 15:57:53 [Server] INFO Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
07.04 15:57:53 [Server] INFO Memory: 2265913360 bytes (2160 MB) / 2640838656 bytes (2518 MB) up to 3817865216 bytes (3641 MB)
07.04 15:57:53 [Server] INFO CPUs: 12
07.04 15:57:53 [Server] INFO JVM Flags: 4 total; -Xmx4096M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512
07.04 15:57:53 [Server] INFO ModLauncher: 8.0.9+86+master.3cf110c
07.04 15:57:53 [Server] INFO ModLauncher launch target: fmlserver
07.04 15:57:53 [Server] INFO ModLauncher naming: srg
07.04 15:57:53 [Server] INFO ModLauncher services: 
07.04 15:57:53 [Server] INFO /mixin-0.8.2.jar mixin PLUGINSERVICE 
07.04 15:57:53 [Server] INFO /eventbus-4.0.0.jar eventbus PLUGINSERVICE 
07.04 15:57:53 [Server] INFO /custom.jar object_holder_definalize PLUGINSERVICE 
07.04 15:57:53 [Server] INFO /custom.jar runtime_enum_extender PLUGINSERVICE 
07.04 15:57:53 [Server] INFO /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
07.04 15:57:53 [Server] INFO /custom.jar capability_inject_definalize PLUGINSERVICE 
07.04 15:57:53 [Server] INFO /custom.jar runtimedistcleaner PLUGINSERVICE 
07.04 15:57:53 [Server] INFO /mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
07.04 15:57:53 [Server] INFO /custom.jar fml TRANSFORMATIONSERVICE 
07.04 15:57:53 [Server] INFO FML: 36.1
07.04 15:57:53 [Server] INFO Forge: net.minecraftforge:36.1.4
07.04 15:57:53 [Server] INFO FML Language Providers: 
07.04 15:57:53 [Server] INFO javafml@36.1
07.04 15:57:53 [Server] INFO minecraft@1
07.04 15:57:53 [Server] INFO kotlinforforge@1.11.0`

**Comment by WhyAreAllTheseTaken** [comment]
This issue is fixed in the newest build. Closing the issue.
