### ISSUE TITLE
Error in datapacks when using the newest version of survive

### ISSUE THREAD

**Issue by Mr-Syntax** [Stereowalker/Survive#138]
Normally i would just roll it back but then i have to roll back serene seasons aswell and then it just cascades out of control

im on version 3.3.2 minecraft 1.16.5 forge. 36.1.31

Reloading ResourceManager: Default, infernal-expansion-forge-1.3.jar, TRansliterationLib-1.0.4.jar, ColdSteel(FORGE_1.16.5)vrs1.0.12.jar, mcw-windows-1.0.3-mc1.16.5.jar, torohealth-1.16.4-forge-4.jar, looot-1.16.4-1.0.0.3.jar, BetterCaves-Forge-1.16.4-1.1.2.jar, froglins-1.16.4-1.0.1.5.jar, YungsApi-1.16.4-Forge-6 - Kopi.jar, guardvillagers-1.16.5.1.2.4.jar, GildingMod-FIXED.jar, HarderSpawners-1.16.5-1.36.0.14.jar, secretrooms-1.16.5-1.0.1.jar, ForgivingVoid_1.16.5-5.2.1.jar, Hornets-0.0.3.jar, SnowRealMagic-1.16.4-2.5.7.jar, dynviewdist-2.0.jar, Paraglider-1.16.5-1.3.1.1.jar, supplementaries-1.16.5-0.13.2.jar, betterendforge-1.16.4-1.6.0.jar, structure_gel-1.16.5-1.7.7.jar, LavaClearView-1.16.2-1.1.0.jar, corpse-1.16.5-1.0.5.jar, Vanilla_Block_Variants-2.2.jar, repurposed_structures-1.16.5-2.7.5-forge.jar, BiomesOPlenty-1.16.5-13.1.0.477-universal.jar, ChunkAnimator-1.16.5-1.2.4.jar, dungeons_plus-1.16.5-1.1.5.jar, CavesAndCliffsBackport-6.1.jar, lycanitesmobs-1.16.5-2.3.2.2.jar, curios-forge-1.16.5-4.0.5.2.jar, betteranimals-1.16.4-5.5.0.jar, YungsExtras-Forge-1.16.4-1.0.jar, Chunk Pregenerator-V1.16-3.0.5.jar, TheAbyss2 1.9.7 1.16.5.jar, majruszs-difficulty-1.16.4-1.0.0.jar, increasemobcap-forge-1.16.2-1.0.1.jar, mcw-roofs-2.0.1-mc1.16.5-4.jar, cfm-7.0.0pre22-1.16.3.jar, netherskeletons2.0.jar, mcw-furniture-2.0.1-mc1.16.5.jar, ItemPhysic_v1.4.18_mc1.16.5.jar, cloth-config-4.11.26-forge.jar, bettas-1.2.1.jar, strayspawn_1.16.5-1.3.jar, ScalingHealth-1.16.5-4.1.5+11.jar, exoticbirds-1.16.4-1.1.0.jar, DynamicTrees-1.16.5-0.10.0-Beta17.jar, DynamicTreesPlus-1.16.5-0.1.0-Beta9.jar, BetterMineshafts-Forge-1.16.4-2.0.4.jar, stables-1.16.5-1.0.1.jar, DarkPaintings-1.16.5-6.0.3.jar, Kiwi-1.16.5-3.5.1.jar, mowziesmobs-1.5.19.jar, DynamicTreesBOP-1.16.5-2.0.4.jar, torchslabmod-1.16.4_v1.6.19.jar, mining_helmet-1.16.5-2.0.1.jar, Bountiful Baubles FORGE-1.16.3-0.0.2.jar, jei-1.16.5-7.7.0.106.jar, AttributeFix-1.16.5-10.1.2.jar, caelus-forge-1.16.5-2.1.3.0.jar, Kobolds-1.3.2.jar, colytra-forge-1.16.5-5.1.1.1.jar, invtweaks-1.16.4-1.0.1.jar, PassableFoliage-1.16.5-2.2.1.jar, untamedwilds-1.16.5-1.2.1.jar, SereneSeasons-1.16.5-4.0.1.119-universal.jar, stoneholm-1.2.2.jar, champions-forge-1.16.5-2.0.1.7.jar, good-nights-sleep-1.16.5-1.2.14.jar, grapple_hooks-1.2.2-33.jar, immersive-portals-0.16-mc1.16.5-forge.jar, ColdsGrappler(Forge1.16.4)vrs1.0.2.jar, forge-1.16.5-36.1.31-universal.jar, Atum-1.16.5-2.2.5.jar, subwild-1.2.1.jar, DynamicSurroundings-1.16.4-4.0.4.2.jar, ironchest-1.16.4-11.2.10.jar, antiqueatlas-5.4.4-forge.jar, dungeonsarise1.16.5-1.2.72a.jar, plonk-1.16.5-9.0.8.jar, physics-mod-1.3.4_forge.jar, pandoras_creatures-1.16.3-2.0.1.jar, MouseTweaks-2.14-mc1.16.2.jar, greekfantasy-16.4.17.jar, SaveYourPets-1.16.2-1.0.0.5.jar, FirstPersonMod-2.0.1.jar, ceilingtorch-1.16.5-v1.12.jar, astikorcarts-1.16.5-1.1.1.jar, majrusz-library-1.16.4-2.0.0.jar, dimdungeons-1.12-forge-1.16.5.jar, whisperwoods-1.16.5-2.0.2.jar, notenoughanimations-1.2.4.jar, Mantle-1.16.5-1.6.109.jar, Croptopia-1.16.4-FORGE-1.4.1.jar, backpacked-1.10.1-1.16.3.jar, Regrowth-1.16.4-1.16.5-1.35.0.19.jar, structurize-0.13.177-ALPHA-universal.jar, appleskin-forge-mc1.16.x-2.0.0.jar, byg-1.2.9.jar, VillagersRespawn-1.16.5-1.36.0.4.jar, LegendOfHerobrine-1.16.5-0.6.2.jar, CosmeticArmorReworked-1.16.5-v3a.jar, wrenchest-1.16.2-v1.0.1.jar, xptome-1.16.5-v2.1.2.jar, DefaultOptions_1.16.5-12.2.1.jar, DungeonsMod-1.16.3-1.3.20.jar, UnionLib-1.16.5-3.3.3.jar, zombiehorsespawn_1.16.5-2.7.jar, extendedslabs-1.16.4-1.4.0.jar, AdditionalBanners-1.16.5-6.0.3.jar, KleeSlabs_1.16.5-9.2.1.jar, TerraForged-1.16.5-0.2.10.jar, EnhancedVisuals_v1.3.31_mc1.16.5.jar, citadel-1.7.1-1.16.5.jar, iceandfire-2.1.8-1.16.5.jar, MutantBeasts-1.16.4-1.1.3.jar, Bookshelf-1.16.5-10.1.11.jar, BotanyPots-1.16.5-7.0.17.jar, BotanyTrees-1.16.5-3.0.5.jar, villagersleashed-1.16.5-1.2.0.jar, ProgressiveBosses-2.2.0-mc1.16.x.jar, mcw-doors-1.0.3-mc1.16.5.jar, shulkerbox-1.16.5-1.0.0.jar, carryon-1.16.5-1.15.5.15.jar, twilightforest-1.16.5-4.0.490-universal.jar, konkrete_1.1.6_MC_1.16.2-1.16.5.jar, out_of_sight-1.16.4-1.0.1.jar, mcw-bridges-1.0.5-mc1.16.5-4.jar, dwmh-1.16.4-0.4.0.2.jar, netherportalspread_1.16.5-5.1.jar, projectvibrantjourneys-1.16.5-3.1.0.jar, EndRemastered-R36.jar, ElenaiDodge2-1.16.X-1.1.0.jar, villagespawnpoint_1.16.5-1.5.jar, Bountiful-1.16.4-3.3.1.jar, CNB-1.16.3_5-1.2.11.jar, geckolib-forge-1.16.5-3.0.41.jar, playerex-1.1.8-1.16.5.jar, gaiadimension-1.16.5-1.3.3.jar, collective-1.16.5-2.26.jar, lostcities-1.16-4.0.9-beta.jar, Survive-1.16.5-3.3.0.jar, carrotslib-mc1.16.5-3.0b5.jar, SpartanWeaponry-1.16.4-2.1.0-beta-4.jar, AI-Improvements-1.16.2-0.3.0.jar, kotlin_libraries-1.0-6.jar, The_Undergarden-1.16.5-0.5.4.jar, enchantwithmob-1.16.5-1.4.6.jar, smallships-1.16.5-1.8.5.jar, BetterAdvancements-1.16.5-0.1.0.108.jar, AbyssalDepths-1.16.5-1.0.1.jar, spiders-2.0-1.16.4-1.0.4.jar, cavebiomes-2.0.jar, Shrines-1.16.5-1.8.1.jar, OldJavaWarning-1.16.5-7.0.1.jar, the-conjurer-1.16.4-1.0.13.jar, dungeons_mobs-1.16.5-1.0.5.jar, abnormals_core-1.16.5-3.2.0.jar, personality-1.16.5-1.0.2.jar, buzzier_bees-1.16.5-3.0.1.jar, reap-1.16.5-1.0.0.jar, toadterror-1.16.4-1.0.0.jar, create-mc1.16.5_v0.3.1c.jar, Waystones_1.16.5-7.6.2.jar, Clumps-6.0.0.25.jar, village-employment-1.16.5-1.4.0.jar, comforts-forge-1.16.5-4.0.1.1.jar, tumbleweed-1.16-0.4.9.jar, CustomPlayerModels-1.16-0.0.14a.jar, OuterEnd-0.2.13.jar, DungeonCrawl-1.16.3-2.2.4.jar, betteranimalsplus-1.16.5-10.2.0.jar, DeadGuysUntitledDeepDark.jar, bedspreads-forge-1.16.5-5.1.0.2.jar, DynamicTreesAtum-1.16.5-1.1.0.jar, walljump-forge-1.16.4-1.3.7.jar, VillagersFollowEmeralds-1.16.5-1.0.0.jar, castle_dungeons-2.2-1.16.5-forge.jar, GoldInRiverMod-Completed_Edition1.16.4.jar, TConstruct-1.16.5-3.0.4.197.jar, Inspirations-1.16.5-1.2.3.37.jar, horsecombatcontrols-1.16.5-1.0.3.jar, weakerspiderwebs_1.16.5-1.7.jar, EnchantmentDescriptions-1.16.5-7.0.12.jar, swingthroughgrass-1.16.4-1.5.3.jar, ToolBelt-1.16.5-1.16.0.jar, mana-and-artifice-1.3.0.6.jar, silent-lib-1.16.3-4.9.6.jar, Jade-1.16.4-2.7.1.jar, CreativeCore_v2.2.0_mc1.16.5.jar, smoothboot-forge-1.16.4-1.2.2.jar, defaultworldtype-1.16.3-2.0.2.jar, extragolems-11.3.1.jar, SpartanShields-1.16.5-2.1.2.jar, mobsunscreen-1.16.5-3.0.4.jar, StorageDrawers-1.16.3-8.2.2.jar, performant-1.16.2-5-3.66m.jar, twoplayersonehorse-1.16.4-2.0.2.jar, Animalium-0.6.3.jar, fins-1.6.1.jar, fancymenu_2.1.0_MC_1.16.2-1.16.5.jar, minecolonies-0.14.224-BETA-universal.jar, workshopsofdoom-1.16.4-1.1.0.1.jar, HunterIllager-1.16.5-1.2.1.jar, illagersweararmor-1.0.4.jar, [BETA]dannys_expansion1.16.3~1.16.4-1.0.6.1.jar, ferritecore-2.0.4-forge.jar, enhancedcelestials-1.0.4-1.16.4.jar, illagers_plus-1.16.4v1.4.1.jar, enchantingbooks-1.2.2.jar, TA2 beginning 1.0.9 1.16.5.jar, valhelsia_core-16.0.9.jar, valhelsia_structures-1.16.5-0.1.2.jar, SoundFilters-0.14_for_1.16.2.jar, overloadedarmorbar-5.1.0.jar, chiselsandbits-0.3.4-RELEASE.jar, BetterFoliage-2.6.5-Forge-1.16.5.jar, better_respawn-1.16.5-1.0.2.jar, DynamicTreesTerraForged-1.16.5-1.0.0.jar
20:32:45.093
Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: LOGGER
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887)
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1864)
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712)
	at net.minecraft.client.Minecraft.func_238192_a_(Minecraft.java:1685)
	at net.minecraft.client.gui.screen.CreateWorldScreen.redirect$bgm000$redirectOnCreateLevel(CreateWorldScreen.java:1222)
	at net.minecraft.client.gui.screen.CreateWorldScreen.func_195352_j(CreateWorldScreen.java:260)
	at net.minecraft.client.gui.screen.CreateWorldScreen.lambda$init$11(CreateWorldScreen.java:205)
	at net.minecraft.client.gui.screen.CreateWorldScreen$$Lambda$28217/1380426847.onPress(Unknown Source)
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33)
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16)
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136)
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27)
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87)
	at net.minecraft.client.MouseHelper$$Lambda$27154/1204062669.run(Unknown Source)
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85)
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175)
	at net.minecraft.client.MouseHelper$$Lambda$27153/1659553366.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:106)
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174)
	at net.minecraft.client.MouseHelper$$Lambda$22026/1232622140.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$498/2085313771.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
Caused by: java.lang.NoSuchFieldError: LOGGER
	at com.stereowalker.survive.resource.ItemConsummableDataManager.lambda$load$2(ItemConsummableDataManager.java:86)
	at com.stereowalker.survive.resource.ItemConsummableDataManager$$Lambda$29556/1838436684.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

i would really appreciate if this could be fixed, cause survive is pretty essential in my pack

thanks for the great mod

**Comment by Stereowalker** [comment]
Please Use UnionLib 3.3.2
