### ISSUE TITLE
Disable Temperature cause Datapack issue

### ISSUE THREAD

**Issue by MrEcko19** [Stereowalker/Survive#167]
Hi,

Disable Temperature System causes this error while creating a world or trying to join an existing one.

"Errors in currently selected Datapacks prevented the world from loading"

**Comment by MrEcko19** [comment]
I found a temporary solution.

It looks like if you load up the client with the Temperature system set in true, and changing it to false with the Configured mod before loading the world works to load it.

Also it seems Temperature not working doing this even without restarting the client for the options to truly load up.

Anyway, this is just some kind of temporary solution, hope you can find a really good one so you can have eveything with the good configuration and join or create worlds freely.

**Comment by Stereowalker** [comment]
Can I get your log files. They could contain something helpful to allow me to figure out what's wrong

**Comment by MrEcko19** [comment]
Sure, I guess you're talking about this ones but tell me if not
[debug.log](https://github.com/Stereowalker/Survive/files/7109850/debug.log)
[latest.log](https://github.com/Stereowalker/Survive/files/7109851/latest.log)

**Comment by FlameyFaucet** [comment]
Caused by: java.lang.IllegalArgumentException: Could not get power type from id 'survive:heat_resistance', as it was not registered!
	at io.github.apace100.origins.power.PowerTypeRegistry.get(PowerTypeRegistry.java:47) ~[?:?]
	at io.github.apace100.origins.origin.OriginManager.handler$zjd000$add(OriginManager.java:529) ~[?:?]
	at io.github.apace100.origins.origin.OriginManager.apply(OriginManager.java:48) ~[?:?]
	at io.github.apace100.origins.origin.OriginManager.func_212853_a_(OriginManager.java:16) ~[?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$13619/2125927135.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$13987/135339969.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:167) ~[?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863) ~[?:?]
	... 36 more
	
epic
