### ISSUE TITLE
[Bug] Crash when breaks a temperature regulator with a plate

### ISSUE THREAD

**Issue by Masromero99** [Stereowalker/Survive#210]
MC Version: 1.18.1
Survive version: 1.18.1-6.1.11
Forge version: 1.18.1 (39.1.0)

Issue:
Minecraft crashes if i break a temperature regulator with any temperature plate in it, but stays normal when i first take the temperature plate and then break the regulator.

Latest log: 
```
[22Mar2022 12:23:40.334] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
	at com.stereowalker.survive.world.level.block.PlatedTemperatureRegulatorBlock.m_7381_(PlatedTemperatureRegulatorBlock.java:55) ~[Survive-1.18.1-6.1.11.jar%2377!/:1.18.1-6.1.11]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60724_(BlockBehaviour.java:691) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.world.level.block.Block.m_49874_(Block.java:256) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.world.level.block.Block.m_49881_(Block.java:290) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.world.level.block.Block.m_6240_(Block.java:359) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:254) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:217) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:187) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:945) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:34) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2386!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 25 more
```

**Comment by Stereowalker** [comment]
Thank you
