### ISSUE TITLE
Player Dedicated Server Error & Crash/Kick

### ISSUE THREAD

**Issue by Proxwian** [Stereowalker/Survive#260]
Forge Version 40.1.80
Survive-1.18.2-7.1.3

When player gets in chunks near snow blocks/snow, error appears and player gets kicked from the server, can't log in

` [19Oct2022 17:07:20.204] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: For input string: "8ii"
	Index: 19
	Listeners:
		0: HIGHEST
		1: ASM: org.jwaresoftware.mcmods.armorunder.xlining.XLiningEventsHandler@187fb817 doUETrackInstall(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		2: ASM: org.jwaresoftware.mcmods.lib.integration.survive.SurviveLinkImpl$TemperatureEventsHandler@49d1476f checkTempBasicAdjustment(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		3: HIGH
		4: ASM: org.jwaresoftware.mcmods.armorunder.xlining.XLiningEventsHandler@187fb817 doHiighPriorityTicking(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		5: NORMAL
		6: ASM: com.rolfmao.upgradednetherite.handlers.EventHandler@5d93a8f9 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		7: ASM: com.rolfmao.upgradednetherite.handlers.ArmorEventHandler@7b32c6b4 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		8: ASM: com.rolfmao.upgradednetherite.handlers.ToolEventHandler@7fe7829f onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		9: ASM: com.rolfmao.upgradednetherite.handlers.HorseArmorEventHandler@195527a9 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		10: net.minecraftforge.eventbus.EventBus$$Lambda$4020/0x00000008017aa1f8@339399cc
		11: net.minecraftforge.eventbus.EventBus$$Lambda$4020/0x00000008017aa1f8@6ffb7bd
		12: ASM: class net.silentchaos512.scalinghealth.event.PetEventHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		13: ASM: class net.silentchaos512.scalinghealth.event.DifficultyEvents onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		14: ASM: class net.silentchaos512.scalinghealth.event.BlightHandler onBlightUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		15: net.minecraftforge.eventbus.EventBus$$Lambda$4020/0x00000008017aa1f8@24bbd115
		16: ASM: class com.endertech.minecraft.mods.adpother.events.EntityEvents onLivingEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		17: ASM: class me.desht.pneumaticcraft.common.debug.DroneDebugger$Listener onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		18: ASM: class com.stereowalker.survive.events.SurviveEvents regulateWetness(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		19: ASM: class com.stereowalker.survive.events.SurviveEvents updateEnvTemperature(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		20: ASM: class com.stereowalker.survive.events.SurviveEvents sendToClient(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		21: ASM: class twilightforest.TFEventListener livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		22: ASM: class com.teamabnormals.allurement.core.other.AllurementEvents onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		23: ASM: class com.teamabnormals.savage_and_ravage.core.other.SREvents onUpdateEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		24: ASM: class com.teamabnormals.savage_and_ravage.core.other.SREvents livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		25: ASM: class com.teamabnormals.buzzier_bees.core.other.BBEvents onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		26: ASM: class com.teamabnormals.neapolitan.core.other.NeapolitanEvents onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		27: ASM: insane96mcp.iguanatweaksreborn.module.farming.feature.LivestockSlowdown@527365f5 slowdownAnimalGrowth(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		28: ASM: insane96mcp.iguanatweaksreborn.module.farming.feature.LivestockSlowdown@527365f5 slowdownBreeding(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		29: ASM: insane96mcp.iguanatweaksreborn.module.farming.feature.LivestockSlowdown@527365f5 slowdownEggLay(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		30: ASM: insane96mcp.iguanatweaksreborn.module.farming.feature.LivestockSlowdown@527365f5 cowMilkTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		31: ASM: class gg.moonflower.pollen.core.forge.PollenCommonForgeEvents onEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		32: ASM: insane96mcp.iguanatweaksreborn.module.misc.feature.VillagerNerf@72b8e780 onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		33: ASM: mod.noobulus.tetrapak.effects.base.RegrowthEffect@31aec30f onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		34: ASM: class mod.noobulus.tetrapak.Mods handlebeltTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		35: ASM: com.github.alexthe666.citadel.server.CitadelEvents@1a629a93 onEntityUpdateDebug(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		36: ASM: class com.sammy.malum.core.events.RuntimeEvents onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		37: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@1a687e0c onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		38: ASM: class L_Ender.cataclysm.event.ServerEventHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		39: ASM: wile.engineersdecor.ModEngineersDecor@8db5155 onPlayerEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		40: ASM: class com.simibubi.create.events.CommonEvents onUpdateLivingEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		41: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem holdingExtendoGripIncreasesRange(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		42: ASM: class com.simibubi.create.content.curiosities.armor.DivingHelmetItem breatheUnderwater(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		43: ASM: class com.simibubi.create.content.curiosities.armor.DivingBootsItem accellerateDescentUnderwater(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		44: net.minecraftforge.eventbus.EventBus$$Lambda$4020/0x00000008017aa1f8@4500c787
		45: net.minecraftforge.eventbus.EventBus$$Lambda$4020/0x00000008017aa1f8@6a726b12
		46: ASM: vazkii.quark.content.tools.module.ParrotEggsModule@17a723ca entityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		47: ASM: vazkii.quark.content.tweaks.module.VexesDieWithTheirMastersModule@6cbc68c9 checkWhetherAlreadyDead(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		48: ASM: vazkii.quark.content.tweaks.module.PoisonPotatoUsageModule@71c7d7d3 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		49: ASM: vazkii.quark.content.tweaks.module.PigLittersModule@4644aaa6 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		50: ASM: vazkii.quark.content.tweaks.module.DragonScalesModule@3af0f3c4 onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		51: net.minecraftforge.eventbus.EventBus$$Lambda$4020/0x00000008017aa1f8@114b7bbe
		52: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@548e3b59 tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		53: net.minecraftforge.eventbus.EventBus$$Lambda$4020/0x00000008017aa1f8@6b8233fb
		54: ASM: blusunrize.immersiveengineering.common.EventHandler@69bae183 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		55: ASM: mekanism.common.lib.radiation.RadiationManager@4071ffc8 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		56: ASM: squeek.appleskin.network.SyncHandler@1bd8136a onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		57: ASM: insane96mcp.iguanatweaksreborn.network.SyncHandler@19a55921 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		58: LOW
		59: ASM: org.jwaresoftware.mcmods.armorunder.xlining.XLiningEventsHandler@187fb817 doLooowPriorityTicking(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		60: LOWEST
		61: ASM: class ovh.corail.tombstone.event.EventHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		62: ASM: org.jwaresoftware.mcmods.armorunder.xlining.XLiningEventsHandler@187fb817 doUETrackUninstall(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		63: ASM: org.jwaresoftware.mcmods.lib.integration.survive.SurviveLinkImpl$TemperatureEventsHandler@49d1476f checkTempSmartAdjustment(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
java.lang.NumberFormatException: For input string: "8ii"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at TRANSFORMER/survive@1.18.2-7.1.3/com.stereowalker.survive.json.property.BlockPropertyHandlerImpl$2.getValue(BlockPropertyHandlerImpl.java:67)
	at TRANSFORMER/survive@1.18.2-7.1.3/com.stereowalker.survive.json.property.BlockPropertyHandlerImpl$2.getValue(BlockPropertyHandlerImpl.java:41)
	at TRANSFORMER/survive@1.18.2-7.1.3/com.stereowalker.survive.events.SurviveEvents.getExactTemperature(SurviveEvents.java:248)
	at TRANSFORMER/survive@1.18.2-7.1.3/com.stereowalker.survive.events.SurviveEvents.lambda$addReload$2(SurviveEvents.java:458)
	at TRANSFORMER/survive@1.18.2-7.1.3/com.stereowalker.survive.events.SurviveEvents.updateEnvTemperature(SurviveEvents.java:169)
	at net.minecraftforge.eventbus.ASMEventHandler_799_SurviveEvents_updateEnvTemperature_LivingUpdateEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.1.80/net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:301)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2214)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.m_8119_(Player.java:235)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.m_129483_(Connection.java:245)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
	at java.base/java.lang.Thread.run(Thread.java:833)

[19Oct2022 17:07:20.276] [Server thread/WARN] [net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /182.232.216.148:40978
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NumberFormatException: For input string: "8ii"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
	at com.stereowalker.survive.json.property.BlockPropertyHandlerImpl$2.getValue(BlockPropertyHandlerImpl.java:67) ~[Survive-1.18.2-7.1.3.jar%23345!/:1.18.2-7.1.3]
	at com.stereowalker.survive.json.property.BlockPropertyHandlerImpl$2.getValue(BlockPropertyHandlerImpl.java:41) ~[Survive-1.18.2-7.1.3.jar%23345!/:1.18.2-7.1.3]
	at com.stereowalker.survive.events.SurviveEvents.getExactTemperature(SurviveEvents.java:248) ~[Survive-1.18.2-7.1.3.jar%23345!/:1.18.2-7.1.3]
	at com.stereowalker.survive.events.SurviveEvents.lambda$addReload$2(SurviveEvents.java:458) ~[Survive-1.18.2-7.1.3.jar%23345!/:1.18.2-7.1.3]
	at com.stereowalker.survive.events.SurviveEvents.updateEnvTemperature(SurviveEvents.java:169) ~[Survive-1.18.2-7.1.3.jar%23345!/:1.18.2-7.1.3]
	at net.minecraftforge.eventbus.ASMEventHandler_799_SurviveEvents_updateEnvTemperature_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:301) ~[forge-1.18.2-40.1.80-universal.jar%23389!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2214) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.2-20220404.173914-srg.jar%23384!/:?]
	... 9 more
[19Oct2022 17:07:20.296] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Proxwian lost connection: Internal server error
[19Oct2022 17:07:20.296] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Proxwian left the game `

**Comment by Proxwian** [comment]
Also I can't rejoin with this error

**Comment by Stereowalker** [comment]
Can you attach the entire log file? Also is this replicable without any of the other mods installed?

**Comment by Proxwian** [comment]
[2022-10-19-1.log](https://github.com/Stereowalker/Survive/files/9830150/2022-10-19-1.log)

**Comment by Proxwian** [comment]
Hmm, now it looks like maybe problem is in Armor Underwear Mod, I'll create issue on its developer GitHub too..

**Comment by benvalkin** [comment]
I've got a similar crash on singleplayer. It's also caused by Integer.parseInt trying to parse "8ii" while ticking the player, but I think the stack trace is a bit different. I think it might be because of snow blocks? 
[crash report](https://github.com/Stereowalker/Survive/files/9838356/crash-2022-10-21_12.38.11-server.txt)

I can try to recreate without other mods later.

**Comment by Proxwian** [comment]
Any news? Seems like critical issue

**Comment by emanuele246gi** [comment]
I'm having this issue too and to me it's not happening in a snowy biome, I'm also in a singleplayer flat world and I can't rejoin back in

**Comment by Catomax262** [comment]
Happened to me. Stereowalker needs to see these more often!

**Comment by Catomax262** [comment]
> Any news? Seems like critical issue

Apparently Stereowalker is not up with these, his top priority are these kind of crashes and he isn't checking for Survive issues very often, i don't like that (even though i completely understand it's real-life things going on)
