### ISSUE TITLE
Internal error when player join sever in 1.19.2

### ISSUE THREAD

**Issue by mlus-asuka** [Stereowalker/Survive#287]
[net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /XXXX
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:510) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.2.11.jar%2367!/:1.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.stereowalker.survive.events.SurviveEvents.sendToClient(SurviveEvents.java:115) ~[Survive-1.19.2-8.0.8.1.jar%23238!/:1.19.2-8.0.8.1]
	at com.stereowalker.unionlib.insert.handler.LivingInsertHandler.lambda$insert$0(LivingInsertHandler.java:11) ~[UnionLib-1.19.2-9.0.3.1-Forge.jar%23317!/:9.0.3.1]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.stereowalker.unionlib.insert.InsertHandler.loopThrough(InsertHandler.java:8) ~[UnionLib-1.19.2-9.0.3.1-Forge.jar%23317!/:9.0.3.1]
	at com.stereowalker.unionlib.insert.handler.LivingInsertHandler.insert(LivingInsertHandler.java:10) ~[UnionLib-1.19.2-9.0.3.1-Forge.jar%23317!/:9.0.3.1]
	at com.stereowalker.unionlib.forge.PlatformHelper.lambda$handleInserts$12(PlatformHelper.java:81) ~[UnionLib-1.19.2-9.0.3.1-Forge.jar%23317!/:9.0.3.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:315) ~[forge-1.19.2-43.2.11-universal.jar%23334!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2251) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:243) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[server-1.19.2-20220805.130853-srg.jar%23329!/:?]
	... 9 more

**Comment by Stereowalker** [comment]
Fixed in 8.0.8.2
