### ISSUE TITLE
Crash - multiple times

### ISSUE THREAD

**Issue by Atlntssplayer** [Stereowalker/Survive#35]
I got 3 crashes, each on the same playthrough.
I'm using "Survive-1.16.3-3.0.2.jar" with Minecraft 1.16.4
This is the 2nd playthrough when I'm using your mod and the first time it seems to cause crashes.
Previously with the same mod and game version (not with the same mod setup though) it didn't cause a crash.

I like your mod, I hope you will maintain it and implement more things. I read your idea about sanity mechanics on the mod's Curse page, that would be awesome.
The temperature mechanic is also good idea. Makes survival much more real but there needs to be some way the player can protect itself against it.
Thx!

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2020.12.16. 6:40
Description: Ticking player

java.lang.ClassCastException: net.minecraft.item.AirItem cannot be cast to net.minecraft.item.ArmorItem
	at com.stereowalker.survive.events.SurviveEvents.updateEnvTemperature(SurviveEvents.java:296) ~[survive:1.16.3-3.0.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_569_SurviveEvents_updateEnvTemperature_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:315) ~[forge:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:APP:imm_ptl_mixins.json:client.MixinLivingEntity_C,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:backpacked:player_init,xf:fml:randompatches:RandomPatches PlayerEntity Transformer,pl:mixin:APP:dankstorage.mixins.json:MixinPlayerEntity,pl:mixin:APP:curiousjetpacks.mixins.json:ironjetpacks.PlayerEntityMixin,pl:mixin:APP:jetboots.mixins.json:PlayerEntityMixin,pl:mixin:APP:quiver.mixins.json:PlayerEntityMixin,pl:mixin:APP:imm_ptl_mixins.json:common.block_manipulation.MixinPlayerEntity_B,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tabletweaks.mixins.json:ServerPlayerReserve,pl:mixin:APP:imm_ptl_mixins.json:common.chunk_sync.MixinServerPlayerEntity,pl:mixin:APP:imm_ptl_mixins.json:common.entity_sync.MixinServerPlayerEntity,pl:mixin:APP:imm_ptl_mixins_forge.json:common.MixinServerPlayerEntity_MA,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:backpacked:creative_inventory_action_fix,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:imm_ptl_mixins.json:client.MixinClientConnection,pl:mixin:A}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.stereowalker.survive.events.SurviveEvents.updateEnvTemperature(SurviveEvents.java:296) ~[survive:1.16.3-3.0.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_569_SurviveEvents_updateEnvTemperature_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:315) ~[forge:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:APP:imm_ptl_mixins.json:client.MixinLivingEntity_C,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:backpacked:player_init,xf:fml:randompatches:RandomPatches PlayerEntity Transformer,pl:mixin:APP:dankstorage.mixins.json:MixinPlayerEntity,pl:mixin:APP:curiousjetpacks.mixins.json:ironjetpacks.PlayerEntityMixin,pl:mixin:APP:jetboots.mixins.json:PlayerEntityMixin,pl:mixin:APP:quiver.mixins.json:PlayerEntityMixin,pl:mixin:APP:imm_ptl_mixins.json:common.block_manipulation.MixinPlayerEntity_B,pl:mixin:A}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 431
	Entity Name: Titanlauncher3950
	Entity's Exact location: 94.55, 63.00, 142.50
	Entity's Block location: World: (94,63,142), Chunk: (at 14,3,14 in 5,8; contains blocks 80,0,128 to 95,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tabletweaks.mixins.json:ServerPlayerReserve,pl:mixin:APP:imm_ptl_mixins.json:common.chunk_sync.MixinServerPlayerEntity,pl:mixin:APP:imm_ptl_mixins.json:common.entity_sync.MixinServerPlayerEntity,pl:mixin:APP:imm_ptl_mixins_forge.json:common.MixinServerPlayerEntity_MA,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:backpacked:creative_inventory_action_fix,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:imm_ptl_mixins.json:client.MixinClientConnection,pl:mixin:A}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

**Comment by Stereowalker** [comment]
I've fixed this issue, so I'm closing this
