### ISSUE TITLE
Server Also Crashing, newer version

### ISSUE THREAD

**Issue by NotoriusQ** [Stereowalker/Survive#39]
[crash-2020-12-23_03.27.35-fml.txt](https://github.com/Stereowalker/Survive/files/5734109/crash-2020-12-23_03.27.35-fml.txt)

Forge 35.1.13 - Latest, 1.16.4

>  [main/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: ITEM_ARMOR_EQUIP_LEATHER
[23.12 03:27:33] [Server] 	Index5
[23.12 03:27:33] [Server] 	Listeners:
[23.12 03:27:33] [Server] 		NORMAL
[23.12 03:27:33] [Server] 		ASM: class com.stereowalker.survive.registries.SurviveRegistryEvents registerFluids(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[23.12 03:27:33] [Server] 		ASM: class com.stereowalker.survive.registries.SurviveRegistryEvents registerAttributes(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[23.12 03:27:33] [Server] 		ASM: class com.stereowalker.survive.registries.SurviveRegistryEvents registerPotions(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[23.12 03:27:33] [Server] 		ASM: class com.stereowalker.survive.registries.SurviveRegistryEvents registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[23.12 03:27:33] [Server] 		ASM: class com.stereowalker.survive.registries.SurviveRegistryEvents registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[23.12 03:27:33] [Server] 		ASM: class com.stereowalker.survive.registries.SurviveRegistryEvents registerEnchantments(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[23.12 03:27:33] [Server] 		ASM: class com.stereowalker.survive.registries.SurviveRegistryEvents registerRecipeSerializers(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[23.12 03:27:33] [Server] 		ASM: class com.stereowalker.survive.registries.SurviveRegistryEvents registerEffects(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[23.12 03:27:33] [Server] java.lang.NoSuchFieldErrorITEM_ARMOR_EQUIP_LEATHER
[23.12 03:27:33] [Server] 	at com.stereowalker.survive.item.SArmorMaterial.<clinit>(SArmorMaterial.java:15)
[23.12 03:27:33] [Server] 	at com.stereowalker.survive.item.SItems.<clinit>(SItems.java:20)
[23.12 03:27:33] [Server] 	at com.stereowalker.survive.registries.SurviveRegistryEvents.registerItems(SurviveRegistryEvents.java:58)
[23.12 03:27:33] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_197_SurviveRegistryEvents_registerItems_Register.invoke(.dynamic)
[23.12 03:27:33] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[23.12 03:27:33] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
[23.12 03:27:33] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56)
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40)
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243)
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230)
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196)
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44)
[23.12 03:27:33] [Server] 	at net.minecraft.server.Main.main(Main.java:95)
[23.12 03:27:33] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23.12 03:27:33] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23.12 03:27:33] [Server] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23.12 03:27:33] [Server] 	at java.lang.reflect.Method.invoke(Method.java:498)
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[23.12 03:27:33] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[23.12 03:27:33] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[23.12 03:27:33] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[23.12 03:27:33] [Server] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[23.12 03:27:33] [Server] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[23.12 03:27:33] [Server] 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[23.12 03:27:33] [Server] 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[23.12 03:27:33] [Server] 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[23.12 03:27:33] [Server] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid survive
[23.12 03:27:33] [Server] java.lang.NoSuchFieldErrorITEM_ARMOR_EQUIP_LEATHER
[23.12 03:27:33] [Server] 	at com.stereowalker.survive.item.SArmorMaterial.<clinit>(SArmorMaterial.java:15) ~[survive:?] {re:classloading}
[23.12 03:27:33] [Server] 	at com.stereowalker.survive.item.SItems.<clinit>(SItems.java:20) ~[survive:?] {re:classloading}
[23.12 03:27:33] [Server] 	at com.stereowalker.survive.registries.SurviveRegistryEvents.registerItems(SurviveRegistryEvents.java:58) ~[survive:?] {re:classloading,pl:runtimedistcleaner:A}
[23.12 03:27:33] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_197_SurviveRegistryEvents_registerItems_Register.invoke(.dynamic) ~[?:?] {}
[23.12 03:27:33] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
[23.12 03:27:33] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.{re:classloading}
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
[23.12 03:27:33] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_{}
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[forge:?] {re:classloading}
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[forge:?] {re:classloading}
[23.12 03:27:33] [Server] 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
[23.12 03:27:33] [Server] 	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
[23.12 03:27:33] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_{}
[23.12 03:27:34] [Multicraft] Skipped 272 lines due to rate limit (100/s)
[23.12 03:27:34] [Server] [main/FATAL] [ne.mi.re.GameData/]: Detected errors during registry event dispatch, rolling back to VANILLA state
[23.12 03:27:35] [Server] [main/FATAL] [ne.mi.re.GameData/]: Detected errors during registry event dispatch, roll back to VANILLA complete
[23.12 03:27:35] [Server] [main/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 5 errors found
[23.12 03:27:35] [Server] [main/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 9e280ba2-9b6a-4b2e-a01f-84102f342b52
[23.12 03:27:35] [Server] [main/INFO] [STDOUT/]: [net.minecraft.crash.CrashReport:func_85057_a:196]: Negative index in crash report handler (16/18)
[23.12 03:27:35] [Server] [main/FATAL] [ne.mi.fm.se.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2020-12-23_03.27.35-fml.txt
[23.12 03:27:35] [Server] ---- Minecraft Crash Report ----
[23.12 03:27:35] [Server] // Don't be sad, have a hug! <3
[23.12 03:27:35] [Server] Time12/23/20 3:27 AM
[23.12 03:27:35] [Server] DescriptionMod loading error has occurred
[23.12 03:27:35] [Server] java.lang.ExceptionMod Loading has failed
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
[23.12 03:27:35] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_{}
[23.12 03:27:35] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_{}
[23.12 03:27:35] [Server] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_{}
[23.12 03:27:35] [Server] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_{}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[custom.jar:35.{}
[23.12 03:27:35] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
[23.12 03:27:35] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
[23.12 03:27:35] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
[23.12 03:27:35] [Server] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
[23.12 03:27:35] [Server] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [custom.jar:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [custom.jar:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [custom.jar:?] {}
[23.12 03:27:35] [Server] A detailed walkthrough of the error, its code path and all known details is as follows:
[23.12 03:27:35] [Server] ---------------------------------------------------------------------------------------
[23.12 03:27:35] [Server] -- Head --
[23.12 03:27:35] [Server] Threadmain
[23.12 03:27:35] [Server] Stacktrace:
[23.12 03:27:35] [Server] 	at com.stereowalker.survive.blocks.SBlocks.<clinit>(SBlocks.java:22) ~[survive:?] {re:classloading}
[23.12 03:27:35] [Server] -- MOD survive --
[23.12 03:27:35] [Server] Details:
[23.12 03:27:35] [Server] 	Mod FileSurvive-1.16.4-3.0.4-deobf.jar
[23.12 03:27:35] [Server] 	Failure messageSurvive (survive) encountered an error during the load_registries event phase
[23.12 03:27:35] [Server] 		java.lang.NoSuchFieldErrorWATER
[23.12 03:27:35] [Server] 	Mod Version1.16.4-3.0.4
[23.12 03:27:35] [Server] 	Mod Issue URLhttps://github.com/Stereowalker/Survive/issues
[23.12 03:27:35] [Server] 	Exception messagejava.lang.NoSuchFieldError: WATER
[23.12 03:27:35] [Server] Stacktrace:
[23.12 03:27:35] [Server] 	at com.stereowalker.survive.blocks.SBlocks.<clinit>(SBlocks.java:22) ~[survive:?] {re:classloading}
[23.12 03:27:35] [Server] 	at com.stereowalker.survive.registries.SurviveRegistryEvents.registerBlocks(SurviveRegistryEvents.java:35) ~[survive:?] {re:classloading,pl:runtimedistcleaner:A}
[23.12 03:27:35] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_196_SurviveRegistryEvents_registerBlocks_Register.invoke(.dynamic) ~[?:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.{re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_{}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
[23.12 03:27:35] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_{}
[23.12 03:27:35] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_{}
[23.12 03:27:35] [Server] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_{}
[23.12 03:27:35] [Server] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_{}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[custom.jar:35.{}
[23.12 03:27:35] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
[23.12 03:27:35] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
[23.12 03:27:35] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
[23.12 03:27:35] [Server] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
[23.12 03:27:35] [Server] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [custom.jar:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [custom.jar:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [custom.jar:?] {}
[23.12 03:27:35] [Server] -- MOD survive --
[23.12 03:27:35] [Server] Details:
[23.12 03:27:35] [Server] 	Mod FileSurvive-1.16.4-3.0.4-deobf.jar
[23.12 03:27:35] [Server] 	Failure messageSurvive (survive) encountered an error during the error event phase
[23.12 03:27:35] [Server] 		java.lang.NoSuchFieldErrorITEM_ARMOR_EQUIP_LEATHER
[23.12 03:27:35] [Server] 	Mod Version1.16.4-3.0.4
[23.12 03:27:35] [Server] 	Mod Issue URLhttps://github.com/Stereowalker/Survive/issues
[23.12 03:27:35] [Server] 	Exception messagejava.lang.NoSuchFieldError: ITEM_ARMOR_EQUIP_LEATHER
[23.12 03:27:35] [Server] Stacktrace:
[23.12 03:27:35] [Server] 	at com.stereowalker.survive.item.SArmorMaterial.<clinit>(SArmorMaterial.java:15) ~[survive:?] {re:classloading}
[23.12 03:27:35] [Server] 	at com.stereowalker.survive.item.SItems.<clinit>(SItems.java:20) ~[survive:?] {re:classloading}
[23.12 03:27:35] [Server] 	at com.stereowalker.survive.registries.SurviveRegistryEvents.registerItems(SurviveRegistryEvents.java:58) ~[survive:?] {re:classloading,pl:runtimedistcleaner:A}
[23.12 03:27:35] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_197_SurviveRegistryEvents_registerItems_Register.invoke(.dynamic) ~[?:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.{re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_{}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
[23.12 03:27:35] [Server] 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[forge:?] {re:classloading}

**Comment by colingoodman** [comment]
I am also having this same issue with my Forge server. I can post my log as well if the developers would like.

**Comment by Coraline77447** [comment]
I am also having the same issue with my modded multiplayer server and so is my friend who helped me make my modded server.

**Comment by Oriansenshi** [comment]
I am also having the same issue. My players on my server were really looking forward to it, and would really like to try this mod out

**Comment by Coraline77447** [comment]
Everyone in this comment section, theres a update for survive mod BUT is it just me or is everyone experiencing the screen being extremely blurry? If so then go turn off tird overlay cause I did so and the blurriness is gone and that the tird overlay is bugged!

**Comment by Stereowalker** [comment]
Yes, there's been a release that fixes this issue
