### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Alfariy20** [Stereowalker/Survive#91]
I get error: java.lang.NoSuchFieldErrror: CHANNEL.

**Comment by Alfariy20** [comment]
Crash log:
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 3/17/21 7:46 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5153/2106662805.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4915/878535710.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cameraoverhaul.mixins.json:modern.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.37.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/875456779.call(Unknown Source) [forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.stereowalker.survive.network.NetRegistry.registerMessages(NetRegistry.java:16) ~[?:1.16.5-3.1.7] {re:classloading}
-- MOD survive --
Details:
	Mod File: Survive-1.16.5-3.1.7.jar
	Failure message: Survive (survive) has failed to load correctly
		java.lang.NoSuchFieldError: CHANNEL
	Mod Version: 1.16.5-3.1.7
	Mod Issue URL: https://github.com/Stereowalker/Survive/issues
	Exception message: java.lang.NoSuchFieldError: CHANNEL
Stacktrace:
	at com.stereowalker.survive.network.NetRegistry.registerMessages(NetRegistry.java:16) ~[?:1.16.5-3.1.7] {re:classloading}
	at com.stereowalker.survive.Survive.<init>(Survive.java:73) ~[?:1.16.5-3.1.7] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:35.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3059/1504325562.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3130/4524471.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1190882792 bytes (1135 MB) / 2882011136 bytes (2748 MB) up to 5607784448 bytes (5348 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6016m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.37.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.37
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.37-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |CREATE_REG|NOSIGNATURE
		FarmersDelight-1.16.3-0.3.2.jar                   |Farmer's Delight              |farmersdelight                |1.16.3-0.3.2        |CREATE_REG|NOSIGNATURE
		physics-mod-1.3.4_forge.jar                       |Physics Mod                   |physicsmod                    |1.0                 |CREATE_REG|NOSIGNATURE
		AmbientSounds_v3.1.5_mc1.16.5.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |CREATE_REG|NOSIGNATURE
		UnionLib-1.16.5-3.2.5.jar                         |UnionLib                      |unionlib                      |3.2.5               |CREATE_REG|NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |CREATE_REG|NOSIGNATURE
		torchslabmod-1.16.4_v1.6.18.jar                   |Torch Slab Mod                |torchslabmod                  |1.6.18              |CREATE_REG|NOSIGNATURE
		CreativeCore_v2.1.0_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |CREATE_REG|NOSIGNATURE
		jei-1.16.4-7.6.1.73.jar                           |Just Enough Items             |jei                           |7.6.1.73            |CREATE_REG|NOSIGNATURE
		fishingreal-1.16.3-1.0.0.jar                      |Fishing Real                  |fishingreal                   |1.0.0               |CREATE_REG|NOSIGNATURE
		physex-0.0.3-A.jar                                |Physex Mod                    |physex                        |0.0.3-A             |CREATE_REG|NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |CREATE_REG|NOSIGNATURE
		PassableFoliage-1.16.4-2.2.0.jar                  |Passable Foliage              |passablefoliage               |2.2.0               |CREATE_REG|NOSIGNATURE
		TerraForged-1.16.4-0.2.9.jar                      |TerraForged                   |terraforged                   |0.2.9               |CREATE_REG|7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		horse_colors-1.16.3+4+5-1.5.6.1.jar               |Realistic Horse Genetics      |horse_colors                  |1.16.3+4+5-1.5.6.1  |CREATE_REG|NOSIGNATURE
		citadel-1.6.2.jar                                 |Citadel                       |citadel                       |1.6.2               |CREATE_REG|NOSIGNATURE
		alexsmobs-1.7.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.7.1               |CREATE_REG|NOSIGNATURE
		betteranimals-1.16.4-5.5.0.jar                    |Cyber's Better Animal Models  |betteranimals                 |5.5.0               |CREATE_REG|NOSIGNATURE
		SereneSeasons-1.16.4-4.0.0.87-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.4-4.0.0.87     |CREATE_REG|NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |CREATE_REG|NOSIGNATURE
		DoubleSlabs-1.16-3.4.10.jar                       |Double Slabs                  |doubleslabs                   |3.4.10              |CREATE_REG|NOSIGNATURE
		Survive-1.16.5-3.1.7.jar                          |Survive                       |survive                       |1.16.5-3.1.7        |ERROR     |NOSIGNATURE
		betteranimalsplus-1.16.4-10.1.0.jar               |Better Animals Plus           |betteranimalsplus             |10.1.0              |CREATE_REG|NOSIGNATURE
		snowundertrees-1.16.4-v1.1.3.jar                  |Snow Under Trees              |snowundertrees                |v1.1.3              |CREATE_REG|NOSIGNATURE
		Survivalist-1.16.3-3.3.1.jar                      |Survivalist                   |survivalist                   |3.3.1               |CREATE_REG|NOSIGNATURE
		RealisticTorches-1.16.5-3.1.2.jar                 |Realistic Torches             |realistictorches              |1.16.5-3.1.2        |CREATE_REG|NOSIGNATURE
		BackTools-1.16.5-10.1.0.jar                       |Back Tools                    |backtools                     |10.1.0              |CREATE_REG|NOSIGNATURE
		SnowRealMagic-1.16.4-2.3.3.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.3.3               |CREATE_REG|NOSIGNATURE
		Kiwi-1.16.5-3.4.2.jar                             |Kiwi                          |kiwi                          |3.4.2               |CREATE_REG|NOSIGNATURE
		ItemPhysic_v1.4.17_mc1.16.5.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |CREATE_REG|NOSIGNATURE
		iChunUtil-1.16.3-10.0.0.jar                       |iChunUtil                     |ichunutil                     |10.0.0              |CREATE_REG|NOSIGNATURE
		FpsReducer-mc1.16.4-1.18.jar                      |FPS Reducer                   |fpsreducer                    |mc1.16.4-1.18       |CREATE_REG|NOSIGNATURE
		cameraoverhaul-1.0-1.16.4 (1).jar                 |Camera Overhaul               |cameraoverhaul                |1.0.0               |CREATE_REG|NOSIGNATURE
		forge-1.16.4-35.1.37-universal.jar                |Forge                         |forge                         |35.1.37             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		exoticbirds-1.16.4-1.1.0.jar                      |Exotic Birds                  |exoticbirds                   |1.1.0               |CREATE_REG|NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |CREATE_REG|NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.2.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.2        |CREATE_REG|NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.3.12.jar           |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.12     |CREATE_REG|b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		B3M-1.16.4-02.jar                                 |Вращение Земли Майнкрафт      |b3m                           |1.16.4-02           |CREATE_REG|NOSIGNATURE
		antiqueatlas-5.4.4-forge.jar                      |Antique Atlas                 |antiqueatlas                  |5.4.4-forge         |CREATE_REG|NOSIGNATURE
	Crash Report UUID: 29a30d2a-3fef-4fbe-bfc6-ddc09c586570
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.5161
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Stereowalker** [comment]
Update UnionLib to the latest version
