### ISSUE TITLE
blocks and plants stop destroying

### ISSUE THREAD

**Issue by r0sso** [Stereowalker/Survive#95]
At random moment, when using survival and unionlib, an error occurs on the server and any blocks and plants stop being destroyed and right click returns these blocks and plants back

[Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.IllegalArgumentException: Can't find attribute unionlib:dig_speed
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233810_d_(AttributeModifierMap.java:21) ~[?:?]
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233804_a_(AttributeModifierMap.java:28) ~[?:?]
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233795_c_(SourceFile:62) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_233637_b_(LivingEntity.java:1729) ~[?:?]
	at com.stereowalker.unionlib.event.BaseGameEvents.setupDigSpeedAttribute(BaseGameEvents.java:24) ~[unionlib:3.2.6]
	at net.minecraftforge.eventbus.ASMEventHandler_34_BaseGameEvents_setupDigSpeedAttribute_BreakSpeed.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:183) ~[forge:?]
	at net.minecraft.entity.player.PlayerEntity.getDigSpeed(PlayerEntity.java:709) ~[?:?]
	at net.minecraft.block.AbstractBlock.func_180647_a(AbstractBlock.java:301) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_185903_a(AbstractBlock.java:503) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:164) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

**Comment by Stereowalker** [comment]
Can I get the version of Survive and UnionLib you're using

**Comment by r0sso** [comment]
game version 1.16.5
UnionLib 3.2.6
Survive 3.1.7

**Comment by Stereowalker** [comment]
And your mod list

**Comment by r0sso** [comment]
Sure

abnormals_core
architectury
calemiUtils
cosmeticArmoredReworked
crafttweaker
create
decorative_blocks
extlights
extraboats
farmersDelight
jei
jei_tweaker
lava_monster
mcw_bridges
mcw_doors
mcw_paintings
mcw_roofs
mcw_windows
mining_helmet
performant
storage_drawers
toolBelt
u_team_core
iseful_railroads
vendings
Waystones
worldedit
XaerosWorldMap

and try UnionLib and Survive
